/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package prolog;


import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import org.jpl7.Query;
/**
/**
 *
 * @author Dulce Bick
 */
public class Humedad extends javax.swing.JFrame {

    /**
     * Creates new form dime
     */
    public Humedad() {
        initComponents();
        setTitle("Humedad Vivero");
        Image icon = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/img/icono.jpg"));
        setIconImage(icon);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        zodiaco = new javax.swing.JFormattedTextField();
        consulta = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        resulto = new javax.swing.JTextArea();
        horossss = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        horossss1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        zodiaco.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                zodiacoKeyTyped(evt);
            }
        });
        getContentPane().add(zodiaco);
        zodiaco.setBounds(330, 90, 70, 40);

        consulta.setBackground(new java.awt.Color(255, 204, 204));
        consulta.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        consulta.setText("Enviar");
        consulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultaActionPerformed(evt);
            }
        });
        consulta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                consultaKeyTyped(evt);
            }
        });
        getContentPane().add(consulta);
        consulta.setBounds(360, 250, 110, 40);

        resulto.setColumns(20);
        resulto.setRows(5);
        jScrollPane1.setViewportView(resulto);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(80, 300, 390, 170);

        horossss.setBackground(new java.awt.Color(255, 255, 255));
        horossss.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        horossss.setForeground(new java.awt.Color(255, 255, 255));
        horossss.setText("Ingrese % de humedad");
        getContentPane().add(horossss);
        horossss.setBounds(30, 80, 290, 50);

        jButton1.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jButton1.setText("OFF");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(550, 390, 110, 30);

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/riego.jpg"))); // NOI18N
        fondo.setText("kl");
        getContentPane().add(fondo);
        fondo.setBounds(-130, 0, 670, 490);

        jButton2.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jButton2.setText("Atras");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(550, 20, 110, 30);

        horossss1.setBackground(new java.awt.Color(255, 255, 255));
        horossss1.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        horossss1.setForeground(new java.awt.Color(255, 255, 255));
        horossss1.setText("Ingrese % de humedad");
        getContentPane().add(horossss1);
        horossss1.setBounds(30, 40, 290, 50);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Aspersores");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(560, 260, 100, 30);

        jButton3.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jButton3.setText("ON");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(550, 320, 110, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void consultaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_consultaKeyTyped

            char car = evt.getKeyChar(); 
            if((car<'a' || car>'z'))
            {
            evt.consume();

            }else{
              //  z.setText(z.getText()+String.valueOf(evt.getKeyChar()));
            }

        // TODO add your handling code here:
    }//GEN-LAST:event_consultaKeyTyped

    private void consultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultaActionPerformed

        
        
   String sig = String.valueOf(zodiaco.getText());
           
           System.out.println(sig);
         
          try {
            String conexion = "consult('horoscopo.pl')";
            Query con = new Query(conexion);
            System.out.println(conexion + "" + (con.hasMoreSolutions() ? "ACEPTADO" : "FALLADO"));
            System.out.println("Iniciando la prueba");
            String consul = "prueba2("+sig+",Y).";
            Query ejecutar = new Query(consul);
            if (ejecutar.hasSolution()) {
           
           System.out.println(" Tu horóscopo es: "+ejecutar.oneSolution().get("Y").toString());
           
           resulto.setText(String.valueOf(ejecutar.oneSolution().get("Y").toString()));
           
             
             
            }
        } catch (Exception e) {
            e.printStackTrace();
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_consultaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
            Vivero a = new Vivero();
            a.setBounds(500,100,680,420);
            a.setResizable(false);
            a.setVisible(true);
            this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void zodiacoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_zodiacoKeyTyped

        char car = evt.getKeyChar();
        if((car<'a' || car>'z'))
        {
            evt.consume();

        }else{
            //  z.setText(z.getText()+String.valueOf(evt.getKeyChar()));
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_zodiacoKeyTyped

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Humedad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Humedad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Humedad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Humedad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Humedad().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton consulta;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel horossss;
    private javax.swing.JLabel horossss1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea resulto;
    private javax.swing.JFormattedTextField zodiaco;
    // End of variables declaration//GEN-END:variables
}
