/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package prolog;

import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import org.jpl7.Query;
import javax.swing.Timer;

/**
 *
 * @author Dulce Bick
 */
public class Temperatura extends javax.swing.JFrame {
 private JLabel etiqueta;  
    /**
     * Creates new form Todo
     */
 
    Timer t;
    int k = 0;
    
    public Temperatura() {
        initComponents();
        setTitle("Temperatura");
        Image icon = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/img/icono.jpg"));
        setIconImage(icon); 
        setSize(1000, 490);
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        compatible = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        resultado = new javax.swing.JLabel();
        resultado3 = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        humedad = new javax.swing.JProgressBar();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        Timer = new javax.swing.JLabel();
        jButtonDetener = new javax.swing.JButton();
        signo2 = new javax.swing.JFormattedTextField();
        enviar = new javax.swing.JButton();
        compatible1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(550, 600));
        setType(java.awt.Window.Type.POPUP);
        getContentPane().setLayout(null);

        compatible.setColumns(20);
        compatible.setRows(5);
        jScrollPane2.setViewportView(compatible);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(80, 250, 470, 140);

        jLabel4.setFont(new java.awt.Font("Rockwell", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 0));
        jLabel4.setText("Informe");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(220, 180, 150, 40);

        jLabel6.setFont(new java.awt.Font("Rockwell", 2, 18)); // NOI18N
        jLabel6.setText("Ingrese el nombre de la parcela:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(680, 10, 290, 40);

        jButton2.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        jButton2.setText("Atras");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(10, 20, 140, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/temperatura.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 670, 450);

        resultado.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        resultado.setForeground(new java.awt.Color(255, 255, 255));
        resultado.setText("Signo");
        resultado.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                resultadoComponentAdded(evt);
            }
        });
        getContentPane().add(resultado);
        resultado.setBounds(230, 320, 330, 40);

        resultado3.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        resultado3.setForeground(new java.awt.Color(255, 255, 255));
        resultado3.setText("Signo");
        resultado3.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                resultado3ComponentAdded(evt);
            }
        });
        getContentPane().add(resultado3);
        resultado3.setBounds(230, 320, 300, 40);

        jProgressBar1.setForeground(new java.awt.Color(0, 102, 0));
        jProgressBar1.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        jProgressBar1.setString("C°");
        getContentPane().add(jProgressBar1);
        jProgressBar1.setBounds(690, 190, 250, 40);

        jLabel2.setText("Temperatura");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(780, 160, 90, 20);

        jLabel5.setText("0");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(690, 170, 10, 14);

        jLabel7.setText("50");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(920, 170, 20, 14);
        getContentPane().add(humedad);
        humedad.setBounds(690, 270, 250, 40);

        jLabel8.setText("Humedad");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(790, 250, 60, 14);

        jLabel9.setText("100%");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(900, 250, 40, 14);

        jLabel10.setText("0%");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(690, 250, 30, 14);

        Timer.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Timer.setForeground(new java.awt.Color(0, 102, 51));
        Timer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(Timer);
        Timer.setBounds(720, 360, 190, 50);

        jButtonDetener.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonDetener.setForeground(new java.awt.Color(204, 0, 51));
        jButtonDetener.setText("Detener");
        jButtonDetener.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonDetener.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDetenerActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonDetener);
        jButtonDetener.setBounds(850, 410, 90, 30);

        signo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signo2ActionPerformed(evt);
            }
        });
        getContentPane().add(signo2);
        signo2.setBounds(700, 60, 240, 40);

        enviar.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        enviar.setText("Enviar");
        enviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enviarActionPerformed(evt);
            }
        });
        enviar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                enviarKeyPressed(evt);
            }
        });
        getContentPane().add(enviar);
        enviar.setBounds(770, 120, 90, 27);

        compatible1.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        compatible1.setForeground(new java.awt.Color(51, 51, 51));
        compatible1.setText("      Planta");
        compatible1.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                compatible1ComponentAdded(evt);
            }
        });
        getContentPane().add(compatible1);
        compatible1.setBounds(730, 320, 150, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

           Vivero a = new Vivero();
           a.setBounds(500,100,680,420);
           a.setVisible(true);
           a.setResizable(false);
           this.setVisible(false);

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void resultadoComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_resultadoComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_resultadoComponentAdded

    private void resultado3ComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_resultado3ComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_resultado3ComponentAdded

    private void jButtonDetenerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDetenerActionPerformed
        t.stop();
    }//GEN-LAST:event_jButtonDetenerActionPerformed
    
    public void calcularTmaxima(){
    
    }
    
    private void enviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enviarActionPerformed

        String planta = String.valueOf(signo2.getText());

        try {
            String conexion = "consult('invernadero.pl')";
            Query con = new Query(conexion);
            System.out.println(conexion + "" + (con.hasMoreSolutions() ? "ACEPTADO" : "FALLADO"));
            System.out.println("Iniciando la prueba");
            String consul = "planta(X,Y,Z).";
            System.out.println("Revision de temperatura");
            String consul1 = "puedeVentilar(T1,T2,T3,T4,T5,T6).";
            Query ejecutar = new Query(consul);

            if (ejecutar.hasSolution()) {                           
                System.out.println(" Tu vivero seleccionado es: "+ejecutar.oneSolution().get("X").toString());
                compatible1.setText(String.valueOf(ejecutar.oneSolution().get("X").toString()));
                compatible.setText(String.valueOf("La planta: "+ejecutar.oneSolution().get("X").toString()));
           }if(ejecutar.hasSolution()){
               System.out.println(" Tu vivero seleccionado es: "+ejecutar.oneSolution().get("Y").toString());
                compatible1.setText(String.valueOf(ejecutar.oneSolution().get("Y").toString()));
                compatible.setText(String.valueOf("La planta: "+ejecutar.oneSolution().get("Y").toString()));
           }if(ejecutar.hasSolution()){
               System.out.println(" Tu vivero seleccionado es: "+ejecutar.oneSolution().get("Z").toString());
                compatible1.setText(String.valueOf(ejecutar.oneSolution().get("Z").toString()));
                compatible.setText(String.valueOf("La planta: "+ejecutar.oneSolution().get("Z").toString()));
           }else{
               System.err.println("La planta seleccionada no existe.");
           }
            
        } catch (Exception e) {
            e.printStackTrace();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_enviarActionPerformed

    private void enviarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_enviarKeyPressed

        char car = evt.getKeyChar();
        if((car<'a' || car>'z'))
        {
            evt.consume();

        }else{
            //z.setText(z.getText()+String.valueOf(evt.getKeyChar()));
        }
    }//GEN-LAST:event_enviarKeyPressed

    private void compatible1ComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_compatible1ComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_compatible1ComponentAdded

    private void signo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signo2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_signo2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Temperatura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Temperatura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Temperatura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Temperatura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Temperatura().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Timer;
    private javax.swing.JTextArea compatible;
    private javax.swing.JLabel compatible1;
    private javax.swing.JButton enviar;
    private javax.swing.JProgressBar humedad;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonDetener;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel resultado;
    private javax.swing.JLabel resultado3;
    private javax.swing.JFormattedTextField signo2;
    // End of variables declaration//GEN-END:variables
}
