/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package prolog;

import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;
import java.util.TimerTask;
import java.util.Timer;
//import java.awt.event.ActionEvent;
//import java.awt.event.ActionListener;
//import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.Icon;
import javax.swing.JLabel;
import org.jpl7.Query;

/**
 *
 * @author Marvinero
 */
public class Temperatura extends javax.swing.JFrame {  
    private JLabel etiqueta;  
    /**
     * Creates new form Todo
     */
 
    Timer t;
    int k = 0;
    
    public Temperatura() {
        initComponents();
        setTitle("Temperatura");
        Image icon = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/img/icono.jpg"));
        setIconImage(icon); 
        setSize(1000, 730);
        //setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        compatible = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        resultado = new javax.swing.JLabel();
        resultado3 = new javax.swing.JLabel();
        jProgressBar5 = new javax.swing.JProgressBar();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        Timer = new javax.swing.JLabel();
        jButtonDetener = new javax.swing.JButton();
        signo2 = new javax.swing.JFormattedTextField();
        enviar = new javax.swing.JButton();
        compatible2 = new javax.swing.JLabel();
        offImage = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        GetTemperatura = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        compatible1 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        onImage1 = new javax.swing.JLabel();
        GetTemperatura1 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jProgressBar2 = new javax.swing.JProgressBar();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        compatibleHumedad = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(550, 600));
        setType(java.awt.Window.Type.POPUP);
        getContentPane().setLayout(null);

        compatible.setColumns(20);
        compatible.setRows(5);
        jScrollPane2.setViewportView(compatible);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(80, 340, 470, 140);

        jLabel4.setFont(new java.awt.Font("Rockwell", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 0));
        jLabel4.setText("Informe");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(230, 260, 150, 40);

        jLabel6.setFont(new java.awt.Font("Rockwell", 2, 18)); // NOI18N
        jLabel6.setText("Ingrese el nombre de la parcela:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(680, 10, 280, 40);

        jButton2.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        jButton2.setText("Atras");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(10, 20, 140, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/temperatura.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 670, 570);

        resultado.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        resultado.setForeground(new java.awt.Color(255, 255, 255));
        resultado.setText("Signo");
        resultado.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                resultadoComponentAdded(evt);
            }
        });
        getContentPane().add(resultado);
        resultado.setBounds(230, 320, 330, 40);

        resultado3.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        resultado3.setForeground(new java.awt.Color(255, 255, 255));
        resultado3.setText("Signo");
        resultado3.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                resultado3ComponentAdded(evt);
            }
        });
        getContentPane().add(resultado3);
        resultado3.setBounds(230, 320, 300, 40);

        jProgressBar5.setForeground(new java.awt.Color(0, 102, 0));
        jProgressBar5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jProgressBar5.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        jProgressBar5.setString("C°");
        getContentPane().add(jProgressBar5);
        jProgressBar5.setBounds(380, 630, 250, 40);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 0));
        jLabel2.setText("Humedad");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(470, 580, 70, 20);

        jLabel5.setText("25");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(120, 610, 20, 14);

        jLabel7.setText("75");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(240, 610, 20, 14);

        jLabel9.setText("100%");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(600, 610, 40, 14);

        jLabel10.setText("0%");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(380, 610, 30, 14);

        Timer.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Timer.setForeground(new java.awt.Color(0, 102, 51));
        Timer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Timer.setText("Temporizador");
        getContentPane().add(Timer);
        Timer.setBounds(690, 620, 130, 40);

        jButtonDetener.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonDetener.setForeground(new java.awt.Color(204, 0, 51));
        jButtonDetener.setText("Detener");
        jButtonDetener.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonDetener.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDetenerActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonDetener);
        jButtonDetener.setBounds(840, 630, 90, 30);

        signo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signo2ActionPerformed(evt);
            }
        });
        getContentPane().add(signo2);
        signo2.setBounds(700, 60, 240, 40);

        enviar.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        enviar.setText("Enviar");
        enviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enviarActionPerformed(evt);
            }
        });
        enviar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                enviarKeyPressed(evt);
            }
        });
        getContentPane().add(enviar);
        enviar.setBounds(770, 120, 90, 27);

        compatible2.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        compatible2.setForeground(new java.awt.Color(51, 51, 51));
        compatible2.setText("Temperatura");
        compatible2.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                compatible2ComponentAdded(evt);
            }
        });
        getContentPane().add(compatible2);
        compatible2.setBounds(790, 260, 80, 40);

        offImage.setText("        Medidor");
        getContentPane().add(offImage);
        offImage.setBounds(720, 420, 80, 150);

        jLabel11.setFont(new java.awt.Font("Trebuchet MS", 3, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 153, 0));
        jLabel11.setText("Planta Seleccionada");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(750, 150, 140, 40);

        GetTemperatura.setFont(new java.awt.Font("Trebuchet MS", 3, 14)); // NOI18N
        GetTemperatura.setForeground(new java.awt.Color(0, 153, 0));
        GetTemperatura.setText("Humedad Vivero");
        getContentPane().add(GetTemperatura);
        GetTemperatura.setBounds(760, 290, 120, 40);

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 51));
        jLabel3.setText("Humidificadores");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(840, 380, 110, 20);

        compatible1.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        compatible1.setForeground(new java.awt.Color(51, 51, 51));
        compatible1.setText("       Planta");
        compatible1.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                compatible1ComponentAdded(evt);
            }
        });
        getContentPane().add(compatible1);
        compatible1.setBounds(740, 190, 160, 40);

        jLabel12.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 102, 51));
        jLabel12.setText("Ventiladores");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(720, 380, 80, 20);

        onImage1.setText("     Medidor");
        getContentPane().add(onImage1);
        onImage1.setBounds(850, 420, 70, 150);

        GetTemperatura1.setFont(new java.awt.Font("Trebuchet MS", 3, 14)); // NOI18N
        GetTemperatura1.setForeground(new java.awt.Color(0, 153, 0));
        GetTemperatura1.setText("Temperatura Vivero");
        getContentPane().add(GetTemperatura1);
        GetTemperatura1.setBounds(750, 230, 140, 40);

        jLabel13.setText("0");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(60, 610, 10, 14);

        jLabel14.setText("50%");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(490, 610, 30, 14);

        jLabel15.setText("100");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(290, 610, 30, 14);

        jProgressBar2.setForeground(new java.awt.Color(0, 102, 0));
        jProgressBar2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jProgressBar2.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        jProgressBar2.setString("C°");
        getContentPane().add(jProgressBar2);
        jProgressBar2.setBounds(60, 630, 250, 40);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 102, 0));
        jLabel16.setText("Temperatura");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(150, 580, 90, 20);

        jLabel17.setText("50");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(180, 610, 20, 14);

        compatibleHumedad.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        compatibleHumedad.setForeground(new java.awt.Color(51, 51, 51));
        compatibleHumedad.setText("Humedad");
        compatibleHumedad.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                compatibleHumedadComponentAdded(evt);
            }
        });
        getContentPane().add(compatibleHumedad);
        compatibleHumedad.setBounds(790, 330, 60, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

      
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

           Vivero a = new Vivero();
           a.setBounds(500,100,680,420);
           a.setVisible(true);
           a.setResizable(false);
           this.setVisible(false);

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void resultadoComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_resultadoComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_resultadoComponentAdded

    private void resultado3ComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_resultado3ComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_resultado3ComponentAdded

    private void jButtonDetenerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDetenerActionPerformed
        //t.stop();
    }//GEN-LAST:event_jButtonDetenerActionPerformed
    
    
    public void imageHumidificador(){
        String path = "/img/on.png";                    
        URL url = this.getClass().getResource(path);                       
        ImageIcon icon = new ImageIcon(url);                  
        onImage1.setIcon(icon);
    }
    
    public void imageHumidificadorOff(){
        String path1 = "/img/off.png"; 
        URL url1 = this.getClass().getResource(path1);
        ImageIcon icon1 = new ImageIcon(url1);
        onImage1.setIcon(icon1);
    }
       
    public int temperaturaInicial = 7;
    public int BHumedad = 69;
    
    private void enviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enviarActionPerformed

        String planta = String.valueOf(signo2.getText());       
     
        try {
            String conexion = "consult('invernadero.pl')";
            Query con = new Query(conexion);
            System.out.println(conexion + "" + (con.hasMoreSolutions() ? "ACEPTADO" : "FALLADO"));
            System.out.println("Iniciando la prueba");
            String consul = "planta(X,Y,Z).";
            System.out.println("Revision de temperatura");
            String consul1 = "puedeVentilar(T1,T2,T3,T4,T5,T6).";
            String consul2 = "puedoHumedecer(T1,T2,T3,T4).";
            Query ejecutar = new Query(consul);
            Query ejecutar1 = new Query(consul1);
            Query ejecutar2 = new Query(consul2);
            
            
            if (ejecutar.hasSolution()){
                switch(signo2.getText()){
                    
                case "repollos":
                    System.out.println(" Tu vivero seleccionado es: "+ejecutar.oneSolution().get("Z").toString());
                    compatible1.setText(String.valueOf(ejecutar.oneSolution().get("Z").toString()));
                    compatible.setText(String.valueOf("La planta: "+ejecutar.oneSolution().get("Z").toString()));  
                    compatible2.setText("C°: "+temperaturaInicial);
                    compatibleHumedad.setText("H:% "+BHumedad);
                    ingresarValorTemperatura();
                    ingresarValorHumedad();
                    
                    if(temperaturaInicial >= 25 && BHumedad >=70){          
                        String path = "/img/on.png";                    
                        URL url = this.getClass().getResource(path);                       
                        ImageIcon icon = new ImageIcon(url);                  
                        offImage.setIcon(icon);
                        imageHumidificador();                       
                    }else{
                        String path1 = "/img/off.png"; 
                        URL url1 = this.getClass().getResource(path1);
                        ImageIcon icon1 = new ImageIcon(url1);
                        offImage.setIcon(icon1);
                        imageHumidificadorOff();
                    }
                    break;
                      
                case "zanahorias":
                    System.out.println(" Tu vivero seleccionado es: "+ejecutar.oneSolution().get("Y").toString());
                    compatible1.setText(String.valueOf(ejecutar.oneSolution().get("Y").toString()));
                    compatible.setText(String.valueOf("La planta: "+ejecutar.oneSolution().get("Y").toString()));
                    compatible2.setText("C°: "+temperaturaInicial);
                    compatibleHumedad.setText("H:% "+BHumedad);
                    ingresarValorTemperatura();
                    ingresarValorHumedad();
                    
                     if(temperaturaInicial >= 25 && BHumedad >=70){          
                        String path = "/img/on.png";                    
                        URL url = this.getClass().getResource(path);                       
                        ImageIcon icon = new ImageIcon(url);                  
                        offImage.setIcon(icon); 
                        imageHumidificador();                        
                        
                    }else{
                        String path1 = "/img/off.png"; 
                        URL url1 = this.getClass().getResource(path1);
                        ImageIcon icon1 = new ImageIcon(url1);
                        offImage.setIcon(icon1);
                         imageHumidificadorOff();
                    }
                    break;
                    
                    case "lechugas":
                    System.out.println("Tu vivero seleccionado es: "+ejecutar.oneSolution().get("X").toString());
                    compatible1.setText(String.valueOf(ejecutar.oneSolution().get("X").toString()));
                    compatible.setText(String.valueOf("La planta: "+ejecutar.oneSolution().get("X").toString()));
                    compatible2.setText("C°: "+temperaturaInicial);   
                    compatibleHumedad.setText("H:% "+BHumedad);
                    ingresarValorTemperatura();
                    ingresarValorHumedad();
                    
                    if(temperaturaInicial >= 25 && BHumedad >=70){          
                        String path = "/img/on.png";                    
                        URL url = this.getClass().getResource(path);                       
                        ImageIcon icon = new ImageIcon(url);                  
                        offImage.setIcon(icon);                                      
                        imageHumidificador();
                        
                    }else{
                        String path1 = "/img/off.png"; 
                        URL url1 = this.getClass().getResource(path1);
                        ImageIcon icon1 = new ImageIcon(url1);
                        offImage.setIcon(icon1);
                        imageHumidificadorOff();
                    }
                }
                           
           }else{
               System.err.println("La planta seleccionada no existe.");
           }
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_enviarActionPerformed
        
    public void getTemperatura(){
        compatible2.getText();
    }
    
    private void enviarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_enviarKeyPressed

        char car = evt.getKeyChar();
        if((car<'a' || car>'z'))
        {
            evt.consume();
        }else{
            //z.setText(z.getText()+String.valueOf(evt.getKeyChar()));
        }
    }//GEN-LAST:event_enviarKeyPressed

    private void compatible2ComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_compatible2ComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_compatible2ComponentAdded

    private void signo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signo2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_signo2ActionPerformed

    private void compatible1ComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_compatible1ComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_compatible1ComponentAdded

    private void compatibleHumedadComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_compatibleHumedadComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_compatibleHumedadComponentAdded
    
    public void ingresarValorTemperatura(){
        int valor = temperaturaInicial;
        jProgressBar2.setValue(valor);
        
    }
    
    public void ingresarValorHumedad(){
        int valor = BHumedad;
        jProgressBar5.setValue(valor);
        
    }
    
    public int contador = 0;
    public void cambiarImagen(){
               
        int velocidad = 2;
        Timer timer;
        TimerTask tarea;
        
        int velmil = velocidad*1000;
        
        Temperatura temperatura = new Temperatura();
        temperatura.setVisible(true);
        
        tarea = new TimerTask() {
            @Override
            public void run() {
                Icon icono;
                
                switch(contador){
                    case 0:
                        contador = 1;
                        icono = new ImageIcon(getClass().getResource("/img/off.png"));
                        temperatura.jLabel3.setIcon(icono);
                        break;
                    case 1: 
                        contador = 2;
                        icono = new ImageIcon(getClass().getResource("/img/on.png"));
                        temperatura.jLabel3.setIcon(icono);
                        break;                                           
                }                
            }
        };
        timer = new Timer();
        timer.scheduleAtFixedRate(tarea, velmil, velmil);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Temperatura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Temperatura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Temperatura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Temperatura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Temperatura().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel GetTemperatura;
    private javax.swing.JLabel GetTemperatura1;
    private javax.swing.JLabel Timer;
    private javax.swing.JTextArea compatible;
    private javax.swing.JLabel compatible1;
    private javax.swing.JLabel compatible2;
    private javax.swing.JLabel compatibleHumedad;
    private javax.swing.JButton enviar;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonDetener;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JProgressBar jProgressBar2;
    private javax.swing.JProgressBar jProgressBar5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel offImage;
    private javax.swing.JLabel onImage1;
    private javax.swing.JLabel resultado;
    private javax.swing.JLabel resultado3;
    private javax.swing.JFormattedTextField signo2;
    // End of variables declaration//GEN-END:variables
}
