/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package prolog;
import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import org.jpl7.Query;
/**
 *
 * @author Dulce Bick
 */
public class Vivero extends javax.swing.JFrame {

    /**
     * Creates new form Horoscopo
     */
    public Vivero() {
        initComponents();
        setTitle("Vivero Inteligente");
        setSize(640, 430);
        Image icon = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/img/icono.jpg"));
        setIconImage(icon);
    }
 private JLabel etiqueta;     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popupMenu1 = new java.awt.PopupMenu();
        dime = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        img = new javax.swing.JLabel();
        resultado1 = new javax.swing.JLabel();

        popupMenu1.setLabel("popupMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setSize(new java.awt.Dimension(500, 500));
        getContentPane().setLayout(null);

        dime.setBackground(new java.awt.Color(102, 255, 255));
        dime.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        dime.setText("Mis plantas");
        dime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dimeActionPerformed(evt);
            }
        });
        getContentPane().add(dime);
        dime.setBounds(360, 230, 220, 40);

        jButton3.setBackground(new java.awt.Color(102, 102, 255));
        jButton3.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        jButton3.setText("Control Invernadero");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(20, 230, 230, 40);

        img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/drone_invernadero.jpg"))); // NOI18N
        img.setMaximumSize(new java.awt.Dimension(673, 420));
        img.setPreferredSize(new java.awt.Dimension(673, 420));
        getContentPane().add(img);
        img.setBounds(0, 0, 630, 390);

        resultado1.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        resultado1.setForeground(new java.awt.Color(255, 255, 255));
        resultado1.setText("Signo");
        resultado1.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                resultado1ComponentAdded(evt);
            }
        });
        getContentPane().add(resultado1);
        resultado1.setBounds(250, 330, 300, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dimeActionPerformed

       // TODO add your handling code here:
    }//GEN-LAST:event_dimeActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
           Temperatura a = new Temperatura();
           a.setBounds(500,100,680,500);
           a.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void resultado1ComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_resultado1ComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_resultado1ComponentAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vivero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vivero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vivero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vivero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vivero().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton dime;
    private javax.swing.JLabel img;
    private javax.swing.JButton jButton3;
    private java.awt.PopupMenu popupMenu1;
    private javax.swing.JLabel resultado1;
    // End of variables declaration//GEN-END:variables
}
